FROM registry.redhat.io/rhel8/mysql-80


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY users.sql /opt/app-root/src



